"""Added retailer table

Revision ID: 68579e301454
Revises: 
Create Date: 2020-09-10 21:49:41.792881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68579e301454'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('document', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('document', 'retailers', ['document'], unique=True)
    op.create_index('email', 'retailers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='retailers')
    op.drop_index('document', table_name='retailers')
    op.drop_table('retailers')
    # ### end Alembic commands ###
